{
 "title": "Kharon Test Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Canary Metric Value",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "kharon_current_canary_metric_value",
     "legendFormat": "{{namespace}}/canary={{canary}}/target={{target}}"
    }
   ]
  },
  {
   "title": "Kharon Test Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "( increase(api_http_errors_total[2m]) / increase(api_http_requests_total[2m]) ) * 100.0",
     "legendFormat": "{{namespace}}/target={{service}} (api={{api}},method={{method}})"
    }
   ]
  },
  {
   "title": "Current Canary Weight",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "kharon_current_canary_weight" }
   ]
  }
 ]
}