apiVersion: batch/v1
kind: Job
metadata:
  name: kharon-gen-req
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - name: worker
        image: centos:7
        command:
        - sh
        - -c
        - >
          for j in {1..800} ;
          do
            for i in {0..2} ;
            do
              curl -w "v1-${i}-0->(%{http_code}) " -s -o /dev/null http://kharon-test-v1-${i}-0:8080/api/greeting && sleep 0.25 ;
            done ;
          done
        imagePullPolicy: IfNotPresent
      restartPolicy: Never