apiVersion: kharon.redhat.com/v1alpha1
kind: Canary
metadata:
  name: deployment-example-canary
spec:
  enabled: true
  targetRef:
    apiVersion: apps/v1
    kind: DeploymentConfig
    name: deployment-example-v1
  canaryAnalysis:
    metricsServer: 'https://prometheus...'
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      threshold: 99
      interval: 1m
      prometheusQuery: ''
    - name: request-duration
      # maximum req duration P99
      # milliseconds
      threshold: 500
      interval: 30s
      prometheusQuery: ''
#status:
#  canaryWeight: 0
#  failedChecks: 0
#  iterations: 0
#  lastAppliedSpec: "14788816656920327485"
#  lastPromotedSpec: "14788816656920327485"
#  # Conditions to wait... => kubectl wait canary/podinfo --for=condition=promoted
#  conditions:
#  - lastTransitionTime: "2019-07-10T08:23:18Z"
#    lastUpdateTime: "2019-07-10T08:23:18Z"
#    message: Canary analysis completed successfully, promotion finished.
#    reason: Succeeded
#    status: "True"
#    type: Promoted
#  releaseHistory:
#  - id: 1
#    name: deployment-example-v1
#    ref:
#      apiVersion: apps/v1
#      kind: DeploymentConfig
#      name: deployment-example-v1
