apiVersion: kharon.redhat.com/v1alpha1
kind: Canary
metadata:
  name: canary-kharon-test
  labels:
    app: kharon-test
spec:
  serviceName: kharon-test
  enabled: true
  type: Native
  canaryAnalysis:
    metricsServer: 'http://prometheus-operated-monitoring.apps.cluster-kharon-eeae.kharon-eeae.open.redhat.com'
    # schedule interval (default 60s)
    interval: 60
    # max number of failed metric checks before rollback
    threshold: 3
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    metric:
      name: error-rate
      # max error rate (5xx responses)
      # percentage (0-100)
      threshold: 2
      operator: 'lt'
      interval: 10
      #prometheusQuery: 'rate(api_http_errors_total{namespace="{{.Namespace}}",service="{{.Spec.TargetRef.Name}}"}[5m])/rate(api_http_requests_total{namespace="{{.Namespace}}",service="{{.Spec.TargetRef.Name}}"}[5m])'
      prometheusQuery: '(sum(api_http_errors_total{namespace="{{.Namespace}}",service="{{.Spec.TargetRef.Name}}"})/sum(api_http_requests_total{namespace="{{.Namespace}}",service="{{.Spec.TargetRef.Name}}"}))*100.0'
      
  targetRefContainerPort: '8080-tcp' # If you don't specify this... maybe the order of ports is not correct and you'll get another port...
  targetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: kharon-test-v1-0-0
  #targetRef:
  #  apiVersion: apps.openshift.io/v1
  #  kind: DeploymentConfig
  #  name: kharon-test-v1-1-0
  #targetRef:
  #  apiVersion: apps.openshift.io/v1
  #  kind: DeploymentConfig
  #  name: kharon-test-v1-2-0
#status:
#  canaryWeight: 0
#  canaryMetricValue: 0.87
#  failedChecks: 0
#  iterations: 0
#  lastAppliedSpec: "14788816656920327485"
#  lastPromotedSpec: "14788816656920327485"
#  # Conditions to wait... => kubectl wait canary/podinfo --for=condition=promoted
#  conditions:
#  - lastTransitionTime: "2019-07-10T08:23:18Z"
#    lastUpdateTime: "2019-07-10T08:23:18Z"
#    message: Canary analysis completed successfully, promotion finished.
#    reason: Succeeded
#    status: "True"
#    type: Promoted
#  releaseHistory:
#  - id: 1
#    name: deployment-example-v1
#    ref:
#      apiVersion: apps/v1
#      kind: DeploymentConfig
#      name: deployment-example-v1
