apiVersion: apps/v1
kind: Deployment
metadata:
  name: kharon-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kharon-operator
  template:
    metadata:
      labels:
        name: kharon-operator
    spec:
      serviceAccountName: kharon-operator
      containers:
        - name: kharon-operator
          # Replace this with the built image name
          image: quay.io/{{QUAY_USERNAME}}/kharon-operator:{{OPERATOR_VERSION}}
          command:
          - kharon-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kharon-operator"
